/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERAZIONI_H_RPCGEN
#define _OPERAZIONI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dir_scan {
	char *dirname;
	int filedim;
};
typedef struct dir_scan dir_scan;

struct rez {
	int charz;
	int worz;
	int linz;
};
typedef struct rez rez;

#define FILEPROG 0x20000013
#define FILEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILE_SCAN 1
extern  rez * file_scan_1(char **, CLIENT *);
extern  rez * file_scan_1_svc(char **, struct svc_req *);
#define DIR_SCAN 2
extern  int * dir_scan_1(dir_scan *, CLIENT *);
extern  int * dir_scan_1_svc(dir_scan *, struct svc_req *);
extern int fileprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILE_SCAN 1
extern  rez * file_scan_1();
extern  rez * file_scan_1_svc();
#define DIR_SCAN 2
extern  int * dir_scan_1();
extern  int * dir_scan_1_svc();
extern int fileprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dir_scan (XDR *, dir_scan*);
extern  bool_t xdr_rez (XDR *, rez*);

#else /* K&R C */
extern bool_t xdr_dir_scan ();
extern bool_t xdr_rez ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERAZIONI_H_RPCGEN */
