/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fattore.h"

bool_t
xdr_input (XDR *xdrs, input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nome, L_NOMI))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operazione, 4))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_judge (XDR *xdrs, judge *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nome, L_NOMI,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->voti))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_output (XDR *xdrs, output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->giudice, N_GIUDICI,
		sizeof (judge), (xdrproc_t) xdr_judge))
		 return FALSE;
	return TRUE;
}
